# Generated by Django 6.0.4 on 2026-05-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_purchase_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='converted_quantity',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Auto-converted to base stock units'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='warehouse_unit_type',
            field=models.CharField(choices=[('Crate', 'Crate'), ('Pack', 'Pack'), ('Bottle', 'Bottle'), ('Container', 'Wine Container')], default='Crate', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Quantity in warehouse units (crates/packs/bottles/containers)'),
        ),
    ]
