# Generated by Django 6.0.4 on 2026-05-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_activitylog_branch_profile_branch'),
        ('inventory', '0011_salessheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allowed_categories',
            field=models.ManyToManyField(blank=True, related_name='allowed_profiles', to='inventory.category'),
        ),
    ]
