# Generated by Django 6.0.4 on 2026-05-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='logo_background_color',
            field=models.CharField(default='#1e293b', help_text='Background color for logo area', max_length=7),
        ),
        migrations.AddField(
            model_name='branch',
            name='secondary_color',
            field=models.CharField(default='#1d4ed8', help_text='Secondary brand color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='branch',
            name='theme_color',
            field=models.CharField(default='#2563eb', help_text='Primary brand color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='branch',
            name='theme_mode',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', help_text='UI theme mode', max_length=10),
        ),
    ]
