# Generated by Django 6.0.4 on 2026-05-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_logo_background_color_branch_secondary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='button_color',
            field=models.CharField(default='#2563eb', help_text='Button primary color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='branch',
            name='card_accent',
            field=models.CharField(default='#2563eb', help_text='Card accent color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='branch',
            name='header_bg',
            field=models.CharField(default='#2563eb', help_text='Header/navbar background color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='branch',
            name='header_text',
            field=models.CharField(default='#ffffff', help_text='Header text color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='branch',
            name='selection_bg',
            field=models.CharField(default='#2563eb', help_text='Selection/highlight background (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='branch',
            name='selection_text',
            field=models.CharField(default='#ffffff', help_text='Selection/highlight text color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='branch',
            name='sidebar_bg',
            field=models.CharField(default='#1e293b', help_text='Sidebar background color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='branch',
            name='sidebar_text',
            field=models.CharField(default='#cbd5e1', help_text='Sidebar text color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='branch',
            name='widget_bg',
            field=models.CharField(default='#16213e', help_text='Dashboard widget background (hex)', max_length=7),
        ),
    ]
