# Generated by Django 6.0.4 on 2026-05-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bottle_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='crate_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_unit',
            field=models.CharField(choices=[('Bottle', 'Bottle'), ('Crate', 'Crate'), ('Piece', 'Piece')], default='Bottle', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('Crate', 'Crate'), ('Carton', 'Carton'), ('Box', 'Box'), ('Piece', 'Piece'), ('Bottle', 'Bottle')], default='Crate', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='units_per_crate',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
