# Generated by Django 6.0.4 on 2026-05-10 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_bottle_quantity_product_crate_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='StockSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_stock', models.PositiveIntegerField(default=0)),
                ('order_stock', models.PositiveIntegerField(default=0)),
                ('total_stock', models.PositiveIntegerField(default=0)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sold_stock', models.PositiveIntegerField(default=0)),
                ('remaining_stock', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_sheets', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Stock Sheet',
                'verbose_name_plural': 'Stock Sheets',
                'ordering': ['-date', 'item__name'],
            },
        ),
    ]
