# Generated by Django 6.0.4 on 2026-05-10 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_product_options_product_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category__name', 'display_order']},
        ),
        migrations.AlterModelOptions(
            name='stocksheet',
            options={'ordering': ['-date', 'item__display_order'], 'verbose_name': 'Stock Sheet', 'verbose_name_plural': 'Stock Sheets'},
        ),
    ]
