# Generated by Django 6.0.4 on 2026-05-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_product_options_alter_stocksheet_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pack_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='units_per_pack',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_unit',
            field=models.CharField(choices=[('Bottle', 'Bottle'), ('Crate', 'Crate'), ('Piece', 'Piece'), ('Pack', 'Pack'), ('Bottle/Can', 'Bottle/Can')], default='Bottle', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('Crate', 'Crate'), ('Carton', 'Carton'), ('Box', 'Box'), ('Piece', 'Piece'), ('Bottle', 'Bottle'), ('Pack', 'Pack')], default='Crate', max_length=50),
        ),
    ]
