# Generated by Django 6.0.4 on 2026-05-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_pack_quantity_product_units_per_pack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shot_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='shots_per_bottle',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_unit',
            field=models.CharField(choices=[('Bottle', 'Bottle'), ('Crate', 'Crate'), ('Piece', 'Piece'), ('Pack', 'Pack'), ('Bottle/Can', 'Bottle/Can'), ('Shot', 'Shot')], default='Bottle', max_length=50),
        ),
    ]
