# Generated by Django 6.0.4 on 2026-05-11 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('inventory', '0008_product_shot_quantity_product_shots_per_bottle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='stocksheet',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_sheets', to='branches.branch'),
        ),
    ]
