# Generated by Django 6.0.4 on 2026-05-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_branch_stocksheet_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksheet',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stocksheet',
            name='moved_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stocksheet',
            name='open_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stocksheet',
            name='order_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stocksheet',
            name='remaining_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stocksheet',
            name='total_stock',
            field=models.IntegerField(default=0),
        ),
    ]
