# Generated by Django 6.0.4 on 2026-05-11 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_button_color_branch_card_accent_and_more'),
        ('inventory', '0010_stocksheet_buying_price_stocksheet_moved_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_stock', models.IntegerField(default=0)),
                ('add_stock', models.IntegerField(default=0)),
                ('total_stock', models.IntegerField(default=0)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sold_stock', models.IntegerField(default=0)),
                ('remaining_stock', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_sheets', to='branches.branch')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_sheets', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Sales Sheet',
                'verbose_name_plural': 'Sales Sheets',
                'ordering': ['-date', 'item__display_order'],
            },
        ),
    ]
