# Generated by Django 6.0.4 on 2026-05-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_salessheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='crate_size',
            field=models.PositiveIntegerField(default=20, help_text='Bottles per crate'),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_size',
            field=models.PositiveIntegerField(default=6, help_text='Bottles per pack'),
        ),
    ]
