# Generated by Django 6.0.4 on 2026-05-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_convert_pet_products_to_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='glasses_per_liter',
            field=models.PositiveIntegerField(default=28, help_text='Glasses per liter (for wine products)'),
        ),
        migrations.AddField(
            model_name='product',
            name='liters_per_unit',
            field=models.PositiveIntegerField(default=5, help_text='Liters per wine container'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_unit',
            field=models.CharField(choices=[('Bottle', 'Bottle'), ('Crate', 'Crate'), ('Piece', 'Piece'), ('Pack', 'Pack'), ('Bottle/Can', 'Bottle/Can'), ('Shot', 'Shot'), ('Glass', 'Glass')], default='Bottle', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('Crate', 'Crate'), ('Carton', 'Carton'), ('Box', 'Box'), ('Piece', 'Piece'), ('Bottle', 'Bottle'), ('Pack', 'Pack'), ('wine_glass', 'Wine (Liters → Glasses)')], default='Crate', max_length=50),
        ),
    ]
