# Generated by Django 6.0.4 on 2026-05-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='backups/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Azibambo Stop_Over', max_length=200)),
                ('business_tagline', models.TextField(blank=True, default='Smart Stock. Smooth Service.')),
                ('business_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('business_phone', models.CharField(blank=True, default='+265 000 000 000', max_length=20)),
                ('business_email', models.EmailField(blank=True, default='info@azibambo.com', max_length=254)),
                ('business_address', models.TextField(blank=True, default='Malawi')),
                ('currency', models.CharField(default='MWK', max_length=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('receipt_footer', models.TextField(blank=True, default='Thank you for your patronage!')),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=10)),
                ('sidebar_color', models.CharField(choices=[('dark', 'Dark'), ('gradient', 'Gradient'), ('light', 'Light')], default='dark', max_length=10)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('low_stock_alert', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
