# Generated by Django 6.0.4 on 2026-05-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='selling_unit',
            field=models.CharField(choices=[('Bottle', 'Bottle'), ('Crate', 'Crate'), ('Piece', 'Piece')], default='Bottle', max_length=20),
        ),
    ]
